name: Generate Release Notes with OpenAI

on:
  release:
    types: [published]

jobs:
  generate-notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate release notes with OpenAI
        run: |
          npx openai-release-notes "$GITHUB_REPOSITORY" "$GITHUB_REF_NAME" > notes.md
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      - name: Upload release notes
        uses: softprops/action-gh-release@v2
        with:
          body_path: notes.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
